### ISSUE TITLE
Setting a field in config

### ISSUE THREAD

**Issue by katafrakt** [vassilevsky/sidekiq-influxdb#1]
Hi! Thank you for this nice gem. I have one enhancement proposal.

My use case is this:

We have a couple of microservices using Sidekiq. I want to track their performance in one series (say `sidekiq_jobs`, but I want to be able to indicate from which service it comes, so I can narrow down the metrics. Would it be possible to add something like this on config level?

For example:

```
chain.add Sidekiq::InfluxDB::ServerMiddleware,
     influxdb_client: InfluxDB::Client.new(options),
     series_name: 'sidekiq_jobs',
     additional_fields: { app: 'microservice_1' }
```

If you agree this is a good thing to add, I can try to work on it myself.

**Comment by vassilevsky** [comment]
Great idea!

Can it be named just `tags` tho?

Can you do it and send a PR?
