### ISSUE TITLE
Idea: exclude some workers

### ISSUE THREAD

**Issue by katafrakt** [vassilevsky/sidekiq-influxdb#3]
There's one more feature idea I would like to discuss. Currently in our organisation we send metrics to InfluxDB synchronously, but I'm thinking about moving it to separate Sidekiq workers, so that Influx failure won't fails whole request or another Sidekiq job and so it can be retries later. In this case I would obviously (or maybe not obviously?) like to exclude those Influx workers from metrics reporting.

How do you feel about adding a config option to exclude some workers (or maybe queues) from sending metrics to Influx?

**Comment by katafrakt** [comment]
I realized I didn't do a great job describing some issue, so here's more background:

We use InfluxDB to gather metrics about Sidekiq workers but also about other things (mainly request times). Those latter are done synchronously in the code by simply calling InfluxDB Ruby client. This, however, is not that good, because the client waits for the metric to be sent (with retries) so if InfluxDB is unavailable for some reason, it stalls the request.

Now, the idea is to spawn a Sidekiq worker which is supposed to send data to InfluxDB. However, with sidekiq-influxdb metrics about those workers would be sent too. This is a lot of data we'd never use, so I want to skip sending Sidekiq stats for those workers and that's why I'd like to exclude some workers or queues from metrics.

Hope it's clearer now.

**Comment by vassilevsky** [comment]
This is a reasonable idea. Every library has a blacklist of classes to exclude. I will gladly accept a pull request with this! Thank you!

**Comment by vassilevsky** [comment]
I've done it myself: #4 
Please take a look and let me know if that's what you wanted.

**Comment by vassilevsky** [comment]
Implemented in v0.4.0 ✨
